TimesheetGeneratorAspNetCoreRazorPages/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TimesheetGeneratorAspNetCoreRazorPages.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "What is this application about?";
        }
    }
}

TimesheetGeneratorAspNetCoreRazorPages/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TimesheetGeneratorAspNetCoreRazorPages.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "How to get in touch?";
        }
    }
}

TimesheetGeneratorAspNetCoreRazorPages/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TimesheetGeneratorAspNetCoreRazorPages.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TimesheetGeneratorAspNetCoreRazorPages/Pages/Index.cshtml.cs
using System;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Globalization;

namespace TimesheetGeneratorAspNetCoreRazorPages.Pages
{
    public class IndexModel : PageModel
    {
        /// <summary>
        /// This method is used for GET http requests.
        /// </summary>
        public void OnGet()
        {
            // Set default form field values.
            CandidateName = string.Empty;
            ClientName = string.Empty;
            JobTitle = string.Empty;
            PlacementStartDate = DateTime.Today;
            PlacementEndDate = PlacementStartDate.AddDays(6);
            PlacementType = "Weekly";

            // Set default validation values.
            Validated = false;
            PlacementStartDateErrorMessage = string.Empty;
            PlacementEndDateErrorMessage = string.Empty;
        }

        /// <summary>
        /// This method is used for http POST requests when button [Generate] is pressed.
        /// </summary>
        public void OnPostGenerate()
        {
            if (ModelState.IsValid)
            {
                // Trim data type text input values.
                CandidateName = CandidateName.Trim();
                ClientName = ClientName.Trim();
                JobTitle = JobTitle.Trim();

                // Validate data type date values here on server side, because client side validation only validates empty fields.
                DateTime startDate;
                if (DateTime.TryParseExact(PlacementStartDate.ToShortDateString(), new string[] { "dd/MM/yyyy" },
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.None, out startDate))
                {
                    DateTime endDate;
                    if (DateTime.TryParseExact(PlacementEndDate.ToShortDateString(), new string[] { "dd/MM/yyyy" },
                        CultureInfo.InvariantCulture,
                        DateTimeStyles.None, out endDate))
                    {
                        // Check if end date is greater than start date.
                        int cmp = PlacementEndDate.CompareTo(PlacementStartDate);
                        if (cmp > 0)
                        {
                            // Trim data type text values.
                            CandidateName = CandidateName.Trim();
                            ClientName = ClientName.Trim();
                            JobTitle = JobTitle.Trim();

                            // Set validation flag.
                            Validated = true;
                        }
                        else if (cmp < 0)
                        {
                            PlacementEndDateErrorMessage = "The Placement End Date is in the past.";
                            // Set validation flag.
                            Validated = false;
                        }
                    }
                    else
                    {
                        PlacementEndDateErrorMessage = "The Placement End Date is invalid. A valid format is dd/MM/yyyy";
                        // Set validation flag.
                        Validated = false;
                    }
                }
                else
                {
                    PlacementStartDateErrorMessage = "The Placement Start Date is invalid. A valid format is dd/MM/yyyy";
                    // Set validation flag.
                    Validated = false;
                }
            }
        }

        #region Model Properties

        [BindProperty, Required, DataType(DataType.Text), StringLength(50, MinimumLength = 3)]
        [Display(Name = "Candidate Name")]
        public string CandidateName { get; set; }

        [BindProperty, Required, DataType(DataType.Text), StringLength(50, MinimumLength = 3)]
        [Display(Name = "Client Name")]
        public string ClientName { get; set; }

        [BindProperty, Required, DataType(DataType.Text), StringLength(50, MinimumLength = 3)]
        [Display(Name = "Job Title")]
        public string JobTitle { get; set; }

        [BindProperty, DataType(DataType.Date), StringLength(10, MinimumLength = 8)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Placement Start Date")]
        public DateTime PlacementStartDate { get; set; }

        [BindProperty, DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Placement End Date")]
        public DateTime PlacementEndDate { get; set; }

        [BindProperty, Required, DataType(DataType.Text)]
        [Display(Name = "Placement Type")]
        public string PlacementType { get; set; }

        // Validate date properties.
        public string PlacementStartDateErrorMessage { get; set; }
        public string PlacementEndDateErrorMessage { get; set; }

        #endregion

        public bool Validated { get; set; }

        #region Methods

        /// <summary>
        /// This method is used to get the header row for http POST requests when button [Create] is pressed.
        /// </summary>
        public string GetHeaderRow()
        {
            StringBuilder result = new StringBuilder("");

            if (Validated)
            {
                result.AppendLine(string.Format(
                    "Candidate Name: {0}<br />Client Name: {1}<br />Job Title: {2}<br />Placement Start Date: {3}<br />PlacementEnd Date: {4}<br />", CandidateName, ClientName, JobTitle, PlacementStartDate, PlacementEndDate));
            }
            return result.ToString();
        }

        /// <summary>
        /// This method is used to get the date range row(s) for http POST requests when button [Create] is pressed.
        /// </summary>
        public string GetDateRangeRow()
        {
            StringBuilder result = new StringBuilder("");

            if (Validated)
            {
                // Get range
                DateTime startDate;

                if (DateTime.TryParseExact(PlacementStartDate.ToShortDateString(), new string[] { "dd/MM/yyyy" },
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.None, out startDate))
                {
                    string[] dates;

                    while (startDate <= PlacementEndDate)
                    {
                        dates = GetRange(PlacementType, startDate);
                        result.AppendLine(string.Format("{0} - {1}<br />", dates[0], dates[1]));
                        startDate = DateTime.Parse(dates[1]).AddDays(1);
                    }
                }
            }
            return result.ToString();
        }

        /// <summary>
        /// This method is called by GetDateRanges() to get a date range by frequency.
        /// </summary>
        public string[] GetRange(string frequency, DateTime startDate)
        {
            string[] result = new string[2];
            DateTime dateRangeBegin = startDate;
            TimeSpan duration = new TimeSpan(0, 0, 0, 0); // One day
            DateTime dateRangeEnd = startDate.Add(duration);

            switch (frequency)
            {
                case "Weekly":
                    dateRangeBegin = startDate;
                    dateRangeEnd = startDate.AddDays(7 - (int)startDate.DayOfWeek);
                    break;

                case "Monthly":
                    duration = new TimeSpan(DateTime.DaysInMonth(startDate.Year, startDate.Month) -1, 0, 0, 0);
                    dateRangeBegin = startDate.AddDays((-1) * startDate.Day + 1);
                    dateRangeEnd = dateRangeBegin.Add(duration);
                    break;
            }

            // Adjust the start date
            if (dateRangeBegin < PlacementStartDate)
            {
                dateRangeBegin = PlacementStartDate;
            }

            // Adjust the end date
            if (dateRangeEnd > PlacementEndDate)
            {
                dateRangeEnd = PlacementEndDate;
            }

            result[0] = dateRangeBegin.ToShortDateString();
            result[1] = dateRangeEnd.ToShortDateString();
            return result;
        }

        #endregion

    }
}

TimesheetGeneratorAspNetCoreRazorPages/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>
    <strong>Sonovate Technical Project</strong>
</p>
<p>
    This is a single-page web application using ASP.NET Core (Mvc, Razor pages).
</p>
<p>
    Requirements:
</p>
<p>
    Hard Rock Recruitment are a recruitment agency who specialise in placing contract software engineers in roles for clients in the tech industry. Day to day, they spend most of their time finding candidates for jobs with their clients (they call these matches ‘placements’), and creating sets of printable timesheets for the candidates to fill out once they have started their contracts.
</p>
<p>
    They believe they can ease the burden of creating the timesheets by commissioning a bespoke application that will allow them to quickly generate timesheets for them to send to candidates.
</p>
<p>
    The app enables the ​user to generate a set of timesheets for a placement, each of which contains the client name, candidate name, job title and timesheet date range such​ ​that​ the user can print them out and send them to a candidate.
</p>

TimesheetGeneratorAspNetCoreRazorPages/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    <strong>Address:</strong> <a href="http://www.sonovate.com/">Sonovate</a><br />
    Second Floor, Golate House<br />
    St Mary Street<br />
    Cardiff<br />
    <abbr title="Postcode">CF10 1DX</abbr>
</address>

<address>
    <strong>Support:</strong> <a href="mailto:lothar.ullrich@gmail.com">lothar.ullrich@gmail.com</a><br />
</address>

TimesheetGeneratorAspNetCoreRazorPages/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home";
}

@{ string[] frequencies = { "Weekly", "Monthly" }; }

<div class="row">
    <div class="col-sm-4">
        <h2>Timesheet Generator</h2>
        <form asp-page-handler="generate" role="form" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label" asp-for="CandidateName"></label>
                <input class="form-control" type="text" asp-for="CandidateName" placeholder="">
                <span asp-validation-for="CandidateName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label" asp-for="ClientName"></label>
                <input class="form-control" type="text" asp-for="ClientName" placeholder="">
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label" asp-for="JobTitle"></label>
                <input class="form-control" type="text" asp-for="JobTitle" placeholder="">
                <span asp-validation-for="JobTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label" asp-for="PlacementStartDate"></label>
                <input class="form-control" type="text" asp-for="PlacementStartDate" placeholder="">
                <span asp-validation-for="PlacementStartDate" class="text-danger"></span>
                <span asp-validation-for="PlacementStartDateErrorMessage" class="text-danger"></span>
                @if (Model != null && Model.Validated && !string.IsNullOrEmpty(Model.PlacementStartDateErrorMessage))
                {
                    <span><label class="text-danger">@Model.PlacementStartDateErrorMessage</label></span>
                }
            </div>
            <div class="form-group">
                <label class="control-label" asp-for="PlacementEndDate"></label>
                <input class="form-control" type="text" asp-for="PlacementEndDate" placeholder="">
                <span asp-validation-for="PlacementEndDate" class="text-danger"></span>
                @if (Model != null && Model.Validated && !string.IsNullOrEmpty(Model.PlacementEndDateErrorMessage))
                {
                    <span><label class="text-danger">@Model.PlacementEndDateErrorMessage</label></span>
                }
            </div>
            <div class="form-group">
                <label asp-for="PlacementType"></label>
                <select class="form-control" asp-for="PlacementType">
                    @foreach (string frequency in frequencies)
                    {
                        <option>@frequency</option>
                    }
                </select>
                <span asp-validation-for="PlacementType" class="text-danger"></span>
            </div>
            <div class="btn-group">
                <button class="btn btn-primary" type="submit">Generate</button>
            </div>
        </form>
    </div>
    <div class="col-sm-8">
        @if (Model != null && Model.Validated)
        {
            <div id="div_print" class="div_print_class">
                <h2>Timesheets</h2>
                <p>
                    @Html.Raw(Model.GetHeaderRow())
                </p>
                <p>
                    @Html.Raw(Model.GetDateRangeRow())
                </p>
            </div>
            <div class="btn-group">
                <input class="btn btn-primary" type="submit" value="Print" onClick="printdiv('div_print');" />
            </div>
        }
    </div>
</div>
<script language="javascript">
    function printdiv(printpage) {
        var headstr = "<html><head><title>Timesheets-@DateTime.Today.Year-@DateTime.Today.Month-@DateTime.Today.Hour-@DateTime.Today.Minute-@DateTime.Today.Minute-@DateTime.Today.Second</title></head><body>";
        var footstr = "</body>";
        var newstr = document.all.item(printpage).innerHTML;
        var oldstr = document.body.innerHTML;
        document.body.innerHTML = headstr + newstr + footstr;
        window.print();
        document.body.innerHTML = oldstr;
        return false;
    }
</script>

TimesheetGeneratorAspNetCoreRazorPages/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TimesheetGeneratorAspNetCoreRazorPages</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/timesheet.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/timesheet.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">TimesheetGeneratorAspNetCoreRazorPages</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Today.Year TimesheetGeneratorAspNetCoreRazorPages</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>